### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by lefoy** [calderalabs/kappa-slack#2]
Hi! I tried using your tool but I get this error message:

``` 
/server/ressources/kappa-slack/lib/kappa-slack/cli.rb:16:in `upload': /server/ressources/kappa-slack/lib/kappa-slack/uploader.rb:11: syntax error, unexpected ',' (SyntaxError)
/server/ressources/kappa-slack/lib/kappa-slack/uploader.rb:119: syntax error, unexpected keyword_end, expecting end-of-input
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from bin/kappa-slack:13:in `<main>'
```

**Comment by ASerger** [comment]
I was able to fix this by running `bundle update`

However I am now getting a SSL certificate error. If I can't resolve, may post.

**Comment by ChristianTheMinery** [comment]
macOS Sierra 10.12.6, encountering the same issue. Tried running `bundle update`. Did not solve the issue.

**Comment by vegerot** [comment]
Have you tried using `brew`'s ruby?
